type_hash = "13770761643547981072722468998856885176094982488914421132658078713404845560680"
expected_hash = "13770761643547981072722468998856885176094982488914421132658078713404845560680"
valid = "1"
